/* FILENAME: llm/dialogue.rs
 * 
 * DESCRIPTION 
 * Struct for Transforming JSON Dialogue which is Generated by Ollama into a Rust Struct
 * for further processing.
 * 
 * NOTES
 * Perhaps we return the Dialogue Object instead of Generation Response?
 * 
 * AUTHOR:    Rezwan Rahman  (RAH22529097)
 * CREATED:   14/11/2024
 * MODIFIED:  14/11/2024
 * 
 */

use serde::{Serialize, Deserialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct Dialogue {
  pub dialogue: String,
  pub npc: String,
  pub choices: Vec<String>
}

