services:
  qdrant:
    container_name: iris-qdrant
    image: qdrant/qdrant
    restart: unless-stopped
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_data:/qdrant/storage

  spacetimedb:
    container_name: iris-spacetimedb
    image: clockworklabs/spacetimedb
    ports:
      - 3000:3000
    environment:
      - RUST_LOG=info
    restart: unless-stopped

  ollama:
    container_name: iris-ollama
    image: ollama/ollama:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  qdrant_data:
    driver: local
  ollama_data:
