services:
  qdrant:
    container_name: iris-qdrant
    image: qdrant/qdrant
    restart: unless-stopped
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
    driver: local
