[package]
name = "iris_gen"
version = "0.1.0"
edition = "2024"

[dependencies]
<<<<<<< HEAD
ollama-rs = { version = "0.2.6", features = ["tool-implementations"] }
ollama-rs-macros = "0.2.6"
reqwest = "0.12.12"
schemars = "0.8.22"
serde = { version = "1.0.218", features = ["derive"] }
=======
ollama-rs = { version = "0.2.6", features = ["ollama-rs-macros"] }
ollama-rs-macros = "0.2.6"
reqwest = "0.12.12"
schemars = "0.8.22"
serde = "1.0.218"
>>>>>>> 84b9dec92ebd2ee4303310d7dfba6d825720debb
thiserror.workspace = true
tokio = { version = "1.43.0", features = ["full"] }
