//! LLMCharacter Node used to create characters which can interact with ollama API.
//! This is the main way we use llms to interact with NPCs.
#![deny(clippy::todo)]

use std::thread;

use crate::llm::LLM;
use crate::memory::MemoryStore;
use crate::utils::parse_json::parse_json;
use godot::builtin::GString;
use godot::classes::{CharacterBody2D, ICharacterBody2D};
use godot::global::godot_print;
use godot::obj::Base;
use godot::prelude::{godot_api, GodotClass};
use ollama_rs::generation::chat::ChatMessage;
use tokio::runtime::Runtime;
use tokio::sync::mpsc;
use tokio::sync::mpsc::{Receiver, Sender};


/// Used to instantiate the LLMCharacter for Godot
/// 
/// ### Fields
/// ---
/// #### Godot Fields
/// - `id` - A GString that stores the ID, can be the the name of the NPC itself.
/// - `profession`  -   A GString which stores the role and job of the character.
/// - `description` -   A GString which stores the general description of the NPC,
///                     describing the general characterisitcs.
/// 
/// - `base`        -   This is the base which the the node inherits of, I choose CharacterBody2D
///                     which is used for NPCs and player characters, and comes with its own
///                     physics system.
/// ---
/// #### System Fields
/// - `memory_store` -  This is where the NPC Memories will be stored using a hashtables which is made up of
///                     a memory ID which is unique and a Memory struct that holds general information of the memory.
/// - `history`      -  This stores the chat histroy of the NPC, allowing for longer and contextually aware conversations.
/// - `generation_channels` - API calls are asynchrounous, thus we need to use channels to allow us to recieve and send mutable data,
///                           from one thread to another.
#[derive(GodotClass)]
#[class(base=CharacterBody2D)]
struct LLMCharacter {
    #[export]
    id: GString,
    #[export]
    profession: GString,
    #[export(multiline)]
    description: GString,

    base: Base<CharacterBody2D>,
    memory_store: MemoryStore,
    history: Vec<ChatMessage>,
    generation_channels: GenerationChannels,
}

/// Generation Channels are used to send and recieve data from different threads.
/// I use channels as blocking the main game thread is unintuitive and will cause the whole game to wait for 
/// dialogue generation.
/// 
/// ### Fields
/// `dialogue_sender`   -   This is an optional sender which expects a string as an argument, used to send
///                         data from one thread to another.
/// `dialogue_reciever` -   Used to recieve data from the sender from another thread.
struct GenerationChannels {
    dialogue_sender: Option<Sender<String>>,
    dialogue_reciever: Option<Receiver<String>>,
}

/// Factory Pattern, we will just create a default version of this as we dont really need customizable
/// generation channels currently.
/// 
/// We can create custom generation channels when we need specific reasons to.
/// 
/// TODO: Perhaps Abstracting this into another file might be better if we want to extend the functioanlity of this.
/// For better modularity.
impl Default for GenerationChannels {
    fn default() -> Self {
        let (sender, reciver) = mpsc::channel(3);

        GenerationChannels {
            dialogue_sender: Some(sender),
            dialogue_reciever: Some(reciver),
        }
    }
}

/// Implement ICharacterBody2D which allows us to have access to Godot functions.
#[godot_api]
impl ICharacterBody2D for LLMCharacter {
    /// Instantiate the LLMCharacter Node
    fn init(base: Base<CharacterBody2D>) -> Self {
        LLMCharacter {
            id: GString::new(),
            profession: GString::new(),
            description: GString::new(),
            base,
            memory_store: MemoryStore::default(),
            history: Vec::new(),
            generation_channels: GenerationChannels::default(),
        }
    }

    /// Process function is responsible for handling events and functions which are called on system updates.
    fn process(&mut self, _delta: f64) {
        self.process_generated_dialogue();
    }
}

#[godot_api]
impl LLMCharacter {
    /// Responsible for handling the dialogue generated by the LLM. Using reciever channel.
    fn process_generated_dialogue(&mut self) {
        if let Some(receiver) = &mut self.generation_channels.dialogue_reciever {
            while let Ok(response) = receiver.try_recv() { 
                let parsed_response = parse_json(response.as_str()).unwrap(); 
                godot_print!("{}", parsed_response)
            }
        }
    }
    
    /// TODO: Refactor This
    #[func]
    fn request_dialogue_generation(&mut self) {
        let mut llm = LLM::default();

        let prompt = "How is your day?";
        let npc_info = self.get_npc_info();
        let combined_prompt = format!("Character Info: {}, Prompt: {}", npc_info, prompt);

        let mut history = self.history.clone();

        let sender = self.generation_channels.dialogue_sender.clone();
        let mut retrieve_memory = self.memory_store.retrieve_recent(3).clone();

        thread::spawn(move || {
            let runtime = Runtime::new().expect("Failed to Create Runtime");

            runtime.block_on(async move {
                if let Ok(response) = llm
                    .generate_dialogue(combined_prompt.as_str(), &mut history, &mut retrieve_memory)
                    .await
                {
                    if let Some(sender) = sender {
                        let _ = sender.send(response.message.content).await;
                    }
                }
            });
        });
    }

    /// Get the NPC Information
    fn get_npc_info(&self) -> String {
        format!(
            "You are role-playing as the following NPC:\n\
              Name: {}\n\
              Profession: {}\n\
              Description: {}\n\
              Please respond in character to the player's inquiries.",
            self.id, self.profession, self.description
        )
    }

    #[signal]
    fn dialogue_generated(&self, response: GString);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_response_channels() {
        let mut channels = GenerationChannels::default();

        if let Some(sender) = &channels.dialogue_sender {
            sender.send("Test Message".to_string()).await.unwrap();
        }

        if let Some(receiver) = &mut channels.dialogue_reciever {
            assert_eq!(receiver.try_recv().unwrap(), "Test Message".to_string());
        }
    }
}
