[package]
name = "iris-api"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
thiserror = "1.0.64"
tokio = "1.40.0"

[dev-dependencies]
anyhow = "1.0.89"
