//! JSON Parse Helper
//!
//! NOTE
//! Using this when there is incorrect JSON Formatting Generated by the LLM,
//! as well as when deepseek-r1 responds with reasoning.

use crate::error::IrisError;
use regex::Regex;

pub fn parse_json(value: &str) -> Result<String, IrisError> {
    let regex_pattern = Regex::new(r"\{(?:[^{}]*|(?R))*\}").unwrap();

    regex_pattern
        .find(value)
        .map(|cap| cap.as_str().to_string())
        .ok_or_else(|| IrisError::FailedToParse("Invalid JSON Format".to_string()))
}
