name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Cache Cargo build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            target
          key: rust-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            rust-${{ runner.os }}-

      - name: List directory contents (debugging)
        run: ls -la
        working-directory: ./

      - name: Build project
        run: cargo build --verbose
        working-directory: ./iris-gen

      - name: Run unit tests only (ignore integration tests)
        run: cargo test --lib --verbose -- --test-threads=4
        working-directory: ./iris-gen

      - name: Run Clippy (Linting)
        run: cargo clippy -- -D warnings
        working-directory: ./iris-gen

      - name: Check Formatting
        run: cargo fmt -- --check
        working-directory: ./iris-gen
